# Generated by Django 6.0.4 on 2026-07-19 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_published", models.BooleanField(default=False)),
                ("current_version", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflows_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "approver_role",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_skippable", models.BooleanField(default=False)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[("approval", "Approval"), ("review", "Review")],
                        default="approval",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "specific_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_stages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("workflow", "name"), ("workflow", "order")},
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "logical_operator",
                    models.CharField(
                        blank=True,
                        choices=[("AND", "AND"), ("OR", "OR")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("eq", "Equals"),
                            ("neq", "Not Equals"),
                            ("gte", "Greater Than or Equal"),
                            ("lte", "Less Than or Equal"),
                            ("in", "In"),
                            ("not_in", "Not In"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("skip_stage", "Skip Stage"),
                            ("add_approval", "Add Approval"),
                            ("route_to", "Route To"),
                            ("terminate", "Terminate"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("action_target", models.JSONField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="workflows.rule",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="workflows.workflow",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="workflows.workflowstage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("changelog", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
    ]
