# Generated by Django 6.0.4 on 2026-07-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowstage",
            name="is_skippable",
        ),
    ]
